services:
  - type: web
    name: webtracker-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: KEY
        sync: false
      - key: NODE_VERSION
        value: 18.0.0
